#!/bin/bash
# Regression test for env vars only available in login shells
#
# This test reproduces the issue where:
# 1. User deploys a module with environment variables
# 2. Env vars are NOT available in current shell
# 3. Env vars are NOT available in new non-login shell (bash from bash)
# 4. Env vars ARE available in new login shell (ssh, new terminal)
#
# Expected behavior: Env vars should be available everywhere
# Current behavior: Only in login shells (bug)

set -e

echo ""
echo "========================================="
echo "Login vs Non-Login Shell Env Test"
echo "========================================="
echo "Reproducing the 'had to run bash again' bug"
echo ""

# Setup test environment
TEST_DIR=$(mktemp -d -t fedpunk-shell-test-XXXXXX)
trap "rm -rf $TEST_DIR" EXIT

echo "Test environment: $TEST_DIR"
echo ""

# Override HOME for isolated testing
export HOME="$TEST_DIR/home"
mkdir -p "$HOME/.config/fedpunk/profile.d"
mkdir -p "$TEST_DIR/etc/profile.d"

# Simulate module deployment generating env config
# Use unique var name to avoid pollution from current shell
UNIQUE_VAR="FEDPUNK_TEST_$$_$(date +%s)"
cat > "$HOME/.config/fedpunk/profile.d/fedpunk-env.sh" <<EOF
#!/bin/sh
# Auto-generated by fedpunk - DO NOT EDIT
export ${UNIQUE_VAR}="deployed_value"
export FEDPUNK_TEST_API="https://api.test.com"
EOF

echo "Simulated module deployment - generated env config at:"
echo "  $HOME/.config/fedpunk/profile.d/fedpunk-env.sh"
echo ""

# Simulate system /etc/profile.d/fedpunk.sh
cat > "$TEST_DIR/etc/profile.d/fedpunk.sh" <<'EOF'
#!/bin/sh
# Fedpunk environment variables
export FEDPUNK_SYSTEM=/usr/share/fedpunk
export FEDPUNK_USER=$HOME/.local/share/fedpunk

# Auto-load user module environment variables
if [ -f "$HOME/.config/fedpunk/profile.d/fedpunk-env.sh" ]; then
    . "$HOME/.config/fedpunk/profile.d/fedpunk-env.sh"
fi
EOF

echo "Created simulated /etc/profile.d/fedpunk.sh"
echo ""

#
# Test 1: Current shell does NOT have env vars (expected)
#
echo "=== Test 1: Current shell after deployment ==="
echo "This simulates: user just ran 'fedpunk module deploy'"
echo ""

if [ -z "$FEDPUNK_TEST_API" ]; then
    echo "  ✓ EXPECTED: FEDPUNK_TEST_API not set in current shell"
    echo "    (User would need to manually source the config)"
else
    echo "  ✗ UNEXPECTED: FEDPUNK_TEST_API is set: $FEDPUNK_TEST_API"
fi

echo ""

#
# Test 2: Non-login shell does NOT have env vars (BUG)
#
echo "=== Test 2: New non-login shell (bash from bash) ==="
echo "This simulates: user runs 'bash' from their current bash shell"
echo ""

# Non-login interactive shell (like running 'bash' from bash)
NONLOGIN_VALUE=$(bash -c "
export HOME='$HOME'
echo \$FEDPUNK_TEST_API
")

if [ -z "$NONLOGIN_VALUE" ]; then
    echo "  ❌ BUG REPRODUCED: FEDPUNK_TEST_API not set in non-login shell"
    echo "    /etc/profile.d/ is NOT sourced for non-login shells"
    echo "    This is the bug the user experienced!"
    BUG_REPRODUCED=1
else
    echo "  ✓ UNEXPECTED: FEDPUNK_TEST_API is set: $NONLOGIN_VALUE"
    echo "    (Test environment might be different from real world)"
fi

echo ""

#
# Test 3: Login shell HAS env vars (works but requires new login)
#
echo "=== Test 3: New login shell (ssh, new terminal) ==="
echo "This simulates: user SSH'ing into container or opening new terminal"
echo ""

# Login shell (sources /etc/profile which sources /etc/profile.d/*)
LOGIN_VALUE=$(bash --login -c "
export HOME='$HOME'
# Manually source profile.d to simulate login shell behavior
. '$TEST_DIR/etc/profile.d/fedpunk.sh'
echo \$FEDPUNK_TEST_API
")

if [ "$LOGIN_VALUE" = "https://api.test.com" ]; then
    echo "  ✓ WORKS: FEDPUNK_TEST_API set in login shell"
    echo "    Value: $LOGIN_VALUE"
    echo "    But user had to start a NEW login shell to get it!"
else
    echo "  ✗ FAIL: FEDPUNK_TEST_API not set even in login shell"
    echo "    Expected: 1"
    echo "    Got: $LOGIN_VALUE"
    exit 1
fi

echo ""

#
# Test 4: User's workaround - running 'bash' might create login shell
#
echo "=== Test 4: User's workaround behavior ==="
echo "When user ran 'bash' again, they might have gotten lucky with:"
echo "  - Container configuration that forces login shells"
echo "  - .bashrc that sources /etc/profile"
echo "  - bash --login being their default"
echo ""

# Try various bash invocations
echo "Testing different bash invocations:"

# Standard non-login
STANDARD=$(bash -c "export HOME='$HOME'; echo \$FEDPUNK_TEST_API")
echo "  bash -c: '$STANDARD' (empty = not set)"

# Interactive non-login
INTERACTIVE=$(bash --init-file /dev/null -i -c "export HOME='$HOME'; echo \$FEDPUNK_TEST_API" 2>/dev/null || echo "")
echo "  bash -i: '$INTERACTIVE' (empty = not set)"

# Login shell
LOGIN=$(bash --login -c "export HOME='$HOME'; . '$TEST_DIR/etc/profile.d/fedpunk.sh'; echo \$FEDPUNK_TEST_API")
echo "  bash --login: '$LOGIN' (should be 'https://api.test.com')"

echo ""

#
# Summary
#
echo "========================================="
if [ -n "$BUG_REPRODUCED" ]; then
    echo "BUG REPRODUCED!"
else
    echo "Bug not reproduced (environment differs)"
fi
echo "========================================="
echo ""
echo "Issue Summary:"
echo "  ❌ Current shell: Env vars NOT available after deployment"
echo "  ❌ Non-login shell (bash from bash): Env vars NOT available"
echo "  ✅ Login shell (new terminal/ssh): Env vars available"
echo ""
echo "Real-world impact:"
echo "  - User deploys module"
echo "  - Tries to use env vars → NOT AVAILABLE"
echo "  - Runs 'bash' → STILL NOT AVAILABLE (unless login shell)"
echo "  - Has to start new terminal/ssh → Finally available"
echo ""
echo "Root cause:"
echo "  /etc/profile.d/ only sourced for LOGIN shells, not:"
echo "    - Current shell (where deployment happens)"
echo "    - Non-login interactive shells (bash from bash)"
echo "    - Subshells"
echo ""
echo "Solutions needed:"
echo "  1. Source config in current shell during deployment"
echo "  2. Add to /etc/bash.bashrc for non-login interactive shells"
echo "  3. Add to /etc/zshrc for zsh"
echo ""
