#!/usr/bin/env fish
# Parameter injection system - generates Fish config with module parameters

# Source dependencies
set -l lib_dir (dirname (status -f))
source "$lib_dir/yq-utils.fish"
source "$lib_dir/module-ref-parser.fish"
source "$lib_dir/module-resolver.fish"
source "$lib_dir/yaml-parser.fish"

function param-parse-module-at-index
    # Parse a module reference at a specific index with custom YAML path
    # Usage: param-parse-module-at-index <yaml-file> <modules-path> <index>
    # modules-path: either ".modules" or ".modules.enabled"
    # Returns: module_url or module_name on one line, then params as KEY=VALUE pairs

    set -l yaml_file $argv[1]
    set -l modules_path $argv[2]
    set -l index $argv[3]

    if not test -f "$yaml_file"
        echo "Error: YAML file not found: $yaml_file" >&2
        return 1
    end

    # Get the module reference at the given index
    # Build yq path - concatenate to avoid Fish array syntax interpretation
    set -l item_path "$modules_path""[$index]"
    set -l ref_type (_yq_safe_eval "$item_path | type" "$yaml_file" 2>/dev/null)

    # Handle empty/null ref_type
    if test -z "$ref_type" -o "$ref_type" = "null" -o "$ref_type" = "!!null"
        # Silently skip - module might not exist at this index
        return 1
    end

    switch "$ref_type"
        case "!!str"
            # Simple string reference (e.g., "essentials" or "https://...")
            set -l module_ref (_yq_safe_eval "$item_path" "$yaml_file" 2>/dev/null)
            if test -n "$module_ref" -a "$module_ref" != "null"
                echo "$module_ref"
                return 0
            end
            return 1

        case "!!map"
            # Object with module and params
            set -l module_ref (_yq_safe_eval "$item_path.module" "$yaml_file" 2>/dev/null)
            if test "$module_ref" = "null" -o -z "$module_ref"
                echo "Error: Object reference missing 'module' key at index $index" >&2
                return 1
            end

            # Output module reference first
            echo "$module_ref"

            # Then output parameters as KEY=VALUE pairs
            set -l param_keys (_yq_safe_eval "$item_path.params | keys | .[]" "$yaml_file" 2>/dev/null)
            for key in $param_keys
                set -l value (_yq_safe_eval "$item_path.params.$key" "$yaml_file" 2>/dev/null)
                echo "$key=$value"
            end
            return 0

        case "*"
            # Unknown type, skip silently
            return 1
    end
end

function param-generate-fish-config
    # Generate Fish config file with all module parameters from YAML config
    # Usage: param-generate-fish-config [yaml-path]
    # If no path provided, reads from ~/.config/fedpunk/fedpunk.yaml
    # Supports two YAML structures:
    #   - mode.yaml: .modules[]
    #   - fedpunk.yaml: .modules.enabled[]

    set -l yaml_path $argv[1]

    # Default to fedpunk.yaml if no path provided
    if test -z "$yaml_path"
        set yaml_path "$HOME/.config/fedpunk/fedpunk.yaml"
    end

    if not test -f "$yaml_path"
        echo "Error: YAML file not found: $yaml_path" >&2
        return 1
    end

    set -l fish_config "$HOME/.config/fish/conf.d/fedpunk-module-params.fish"

    # Ensure directory exists
    set -l config_dir (dirname "$fish_config")
    if not test -d "$config_dir"
        mkdir -p "$config_dir"
    end

    # Start building Fish config as an array (one line per element)
    set -l config_lines
    set -a config_lines "#!/usr/bin/env fish"
    set -a config_lines "# Auto-generated by fedpunk - DO NOT EDIT"
    set -a config_lines "# Regenerate with: fedpunk apply"
    set -a config_lines "# Source: $yaml_path"
    set -a config_lines ""

    # Determine which path to use (.modules[] or .modules.enabled[])
    set -l modules_path ".modules"
    set -l enabled_count (_yq_safe_eval '.modules.enabled | length' "$yaml_path" 2>/dev/null)

    # If .modules.enabled exists and has items, use it
    if test -n "$enabled_count" -a "$enabled_count" != "null" -a "$enabled_count" != "0"
        set modules_path ".modules.enabled"
    end

    # Get count of modules
    set -l count (_yq_safe_eval "$modules_path | length" "$yaml_path" 2>/dev/null)

    if test "$count" = "0" -o "$count" = "null"
        # No modules, create empty file
        printf "%s\n" $config_lines > "$fish_config"
        return 0
    end

    # Parse each module (using modified module-ref-parse-from-path)
    for i in (seq 0 (math $count - 1))
        set -l parse_result (param-parse-module-at-index "$yaml_path" "$modules_path" $i)
        or continue

        # In Fish, command substitution creates an array (one element per line)
        # First element is module reference, rest are params
        set -l module_ref $parse_result[1]
        set -l user_params $parse_result[2..-1]

        # Resolve module path to get the actual module.yaml
        set -l module_path (module-resolve-path "$module_ref" 2>/dev/null)

        # Get module name from module.yaml (preferred) or fallback to extracted name
        set -l module_name
        set -l module_yaml ""
        if test -n "$module_path" -a -f "$module_path/module.yaml"
            set module_yaml "$module_path/module.yaml"
            set module_name (_yq_safe_eval '.module.name' "$module_yaml" 2>/dev/null)
        end

        # Fallback to extracted name if module.yaml doesn't have a name
        if test -z "$module_name" -o "$module_name" = "null"
            set module_name (module-ref-extract-name "$module_ref")
        end

        set -l module_name_upper (string upper (string replace -a '-' '_' "$module_name"))

        # Collect all params: defaults from module.yaml + user overrides
        set -l param_keys
        set -l param_values

        # First, get defaults from module's parameters: section
        if test -n "$module_yaml"
            set -l def_keys (_yq_safe_eval '.parameters | keys | .[]' "$module_yaml" 2>/dev/null)
            for key in $def_keys
                set -l default_val (_yq_safe_eval ".parameters.$key.default" "$module_yaml" 2>/dev/null)
                if test -n "$default_val" -a "$default_val" != "null"
                    set -a param_keys "$key"
                    set -a param_values "$default_val"
                end
            end
        end

        # Then, apply user-provided params (override defaults)
        for param in $user_params
            set -l parts (string split -m 1 '=' -- $param)
            if test (count $parts) -eq 2
                set -l key $parts[1]
                set -l value $parts[2]

                # Check if key already exists (from defaults)
                set -l found_idx 0
                for idx in (seq (count $param_keys))
                    if test "$param_keys[$idx]" = "$key"
                        set found_idx $idx
                        break
                    end
                end

                if test $found_idx -gt 0
                    # Override existing default
                    set param_values[$found_idx] "$value"
                else
                    # Add new param
                    set -a param_keys "$key"
                    set -a param_values "$value"
                end
            end
        end

        # Skip if no params at all
        if test (count $param_keys) -eq 0
            continue
        end

        # Add comment for this module
        set -a config_lines ""
        set -a config_lines "# Parameters for: $module_name"

        # Add each parameter
        for idx in (seq (count $param_keys))
            set -l key $param_keys[$idx]
            set -l value $param_values[$idx]

            # Convert key to uppercase
            set -l key_upper (string upper (string replace -a '-' '_' "$key"))

            # Build env var name: FEDPUNK_PARAM_<MODULE>_<KEY>
            set -l env_var_name "FEDPUNK_PARAM_$module_name_upper"_"$key_upper"

            # Escape value for Fish string
            set -l escaped_value (string replace -a '\\' '\\\\' "$value")
            set escaped_value (string replace -a '"' '\\"' "$escaped_value")

            set -a config_lines "set -gx $env_var_name \"$escaped_value\""
        end
    end

    # Write to file
    printf "%s\n" $config_lines > "$fish_config"
    echo "Generated parameter config: $fish_config"
    return 0
end
