#!/usr/bin/env fish
# Parameter injection system - generates Fish config with module parameters

# Source dependencies
set -l lib_dir (dirname (status -f))
source "$lib_dir/module-ref-parser.fish"
source "$lib_dir/module-resolver.fish"
source "$lib_dir/yaml-parser.fish"

function param-generate-fish-config
    # Generate Fish config file with all module parameters from mode.yaml
    # Usage: param-generate-fish-config <mode-yaml-path>
    set -l mode_yaml $argv[1]

    if not test -f "$mode_yaml"
        echo "Error: Mode YAML not found: $mode_yaml" >&2
        return 1
    end

    set -l fish_config "$HOME/.config/fish/conf.d/fedpunk-module-params.fish"

    # Start building Fish config as an array (one line per element)
    set -l config_lines
    set -a config_lines "#!/usr/bin/env fish"
    set -a config_lines "# Auto-generated by fedpunk - DO NOT EDIT"
    set -a config_lines "# Regenerate with: fedpunk apply"
    set -a config_lines "# Source: $mode_yaml"
    set -a config_lines ""

    # Get count of modules
    set -l count (yq eval '.modules | length' "$mode_yaml" 2>/dev/null)

    if test "$count" = "0" -o "$count" = "null"
        # No modules, create empty file
        printf "%s\n" $config_lines > "$fish_config"
        return 0
    end

    # Parse each module
    for i in (seq 0 (math $count - 1))
        set -l parse_result (module-ref-parse "$mode_yaml" $i)
        or continue

        # In Fish, command substitution creates an array (one element per line)
        # First element is module reference, rest are params
        set -l module_ref $parse_result[1]
        set -l params $parse_result[2..-1]

        # Skip if no params
        if test (count $params) -eq 0
            continue
        end

        # Resolve module path to get the actual module.yaml
        set -l module_path (module-resolve-path "$module_ref" 2>/dev/null)

        # Get module name from module.yaml (preferred) or fallback to extracted name
        set -l module_name
        if test -n "$module_path" -a -f "$module_path/module.yaml"
            set module_name (yq eval '.module.name' "$module_path/module.yaml" 2>/dev/null)
        end

        # Fallback to extracted name if module.yaml doesn't have a name
        if test -z "$module_name" -o "$module_name" = "null"
            set module_name (module-ref-extract-name "$module_ref")
        end

        set -l module_name_upper (string upper (string replace -a '-' '_' "$module_name"))

        # Add comment for this module
        set -a config_lines ""
        set -a config_lines "# Parameters for: $module_name"

        # Add each parameter
        for param in $params
            set -l parts (string split '=' -- $param)
            if test (count $parts) -eq 2
                set -l key $parts[1]
                set -l value $parts[2]

                # Convert key to uppercase
                set -l key_upper (string upper (string replace -a '-' '_' "$key"))

                # Build env var name: FEDPUNK_PARAM_<MODULE>_<KEY>
                set -l env_var_name "FEDPUNK_PARAM_$module_name_upper"_"$key_upper"

                # Escape value for Fish string
                set -l escaped_value (string replace -a '\\' '\\\\' "$value")
                set -l escaped_value (string replace -a '"' '\\"' "$escaped_value")

                set -a config_lines "set -gx $env_var_name \"$escaped_value\""
            end
        end
    end

    # Write to file
    printf "%s\n" $config_lines > "$fish_config"
    echo "Generated parameter config: $fish_config"
    return 0
end
